// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"
	v1beta1 "sigs.k8s.io/kueue/apis/kueue/v1beta1"
	kueuev1beta1 "sigs.k8s.io/kueue/client-go/applyconfiguration/kueue/v1beta1"
	typedkueuev1beta1 "sigs.k8s.io/kueue/client-go/clientset/versioned/typed/kueue/v1beta1"
)

// fakeMultiKueueConfigs implements MultiKueueConfigInterface
type fakeMultiKueueConfigs struct {
	*gentype.FakeClientWithListAndApply[*v1beta1.MultiKueueConfig, *v1beta1.MultiKueueConfigList, *kueuev1beta1.MultiKueueConfigApplyConfiguration]
	Fake *FakeKueueV1beta1
}

func newFakeMultiKueueConfigs(fake *FakeKueueV1beta1) typedkueuev1beta1.MultiKueueConfigInterface {
	return &fakeMultiKueueConfigs{
		gentype.NewFakeClientWithListAndApply[*v1beta1.MultiKueueConfig, *v1beta1.MultiKueueConfigList, *kueuev1beta1.MultiKueueConfigApplyConfiguration](
			fake.Fake,
			"",
			v1beta1.SchemeGroupVersion.WithResource("multikueueconfigs"),
			v1beta1.SchemeGroupVersion.WithKind("MultiKueueConfig"),
			func() *v1beta1.MultiKueueConfig { return &v1beta1.MultiKueueConfig{} },
			func() *v1beta1.MultiKueueConfigList { return &v1beta1.MultiKueueConfigList{} },
			func(dst, src *v1beta1.MultiKueueConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.MultiKueueConfigList) []*v1beta1.MultiKueueConfig {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta1.MultiKueueConfigList, items []*v1beta1.MultiKueueConfig) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
