/*

 */
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"
	v1beta1 "sigs.k8s.io/kueue/apis/kueue/v1beta1"
	kueuev1beta1 "sigs.k8s.io/kueue/client-go/applyconfiguration/kueue/v1beta1"
	typedkueuev1beta1 "sigs.k8s.io/kueue/client-go/clientset/versioned/typed/kueue/v1beta1"
)

// fakeAdmissionChecks implements AdmissionCheckInterface
type fakeAdmissionChecks struct {
	*gentype.FakeClientWithListAndApply[*v1beta1.AdmissionCheck, *v1beta1.AdmissionCheckList, *kueuev1beta1.AdmissionCheckApplyConfiguration]
	Fake *FakeKueueV1beta1
}

func newFakeAdmissionChecks(fake *FakeKueueV1beta1) typedkueuev1beta1.AdmissionCheckInterface {
	return &fakeAdmissionChecks{
		gentype.NewFakeClientWithListAndApply[*v1beta1.AdmissionCheck, *v1beta1.AdmissionCheckList, *kueuev1beta1.AdmissionCheckApplyConfiguration](
			fake.Fake,
			"",
			v1beta1.SchemeGroupVersion.WithResource("admissionchecks"),
			v1beta1.SchemeGroupVersion.WithKind("AdmissionCheck"),
			func() *v1beta1.AdmissionCheck { return &v1beta1.AdmissionCheck{} },
			func() *v1beta1.AdmissionCheckList { return &v1beta1.AdmissionCheckList{} },
			func(dst, src *v1beta1.AdmissionCheckList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.AdmissionCheckList) []*v1beta1.AdmissionCheck {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta1.AdmissionCheckList, items []*v1beta1.AdmissionCheck) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
