// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"
	v1beta1 "sigs.k8s.io/kueue/apis/kueue/v1beta1"
	kueuev1beta1 "sigs.k8s.io/kueue/client-go/applyconfiguration/kueue/v1beta1"
	typedkueuev1beta1 "sigs.k8s.io/kueue/client-go/clientset/versioned/typed/kueue/v1beta1"
)

// fakeMultiKueueClusters implements MultiKueueClusterInterface
type fakeMultiKueueClusters struct {
	*gentype.FakeClientWithListAndApply[*v1beta1.MultiKueueCluster, *v1beta1.MultiKueueClusterList, *kueuev1beta1.MultiKueueClusterApplyConfiguration]
	Fake *FakeKueueV1beta1
}

func newFakeMultiKueueClusters(fake *FakeKueueV1beta1) typedkueuev1beta1.MultiKueueClusterInterface {
	return &fakeMultiKueueClusters{
		gentype.NewFakeClientWithListAndApply[*v1beta1.MultiKueueCluster, *v1beta1.MultiKueueClusterList, *kueuev1beta1.MultiKueueClusterApplyConfiguration](
			fake.Fake,
			"",
			v1beta1.SchemeGroupVersion.WithResource("multikueueclusters"),
			v1beta1.SchemeGroupVersion.WithKind("MultiKueueCluster"),
			func() *v1beta1.MultiKueueCluster { return &v1beta1.MultiKueueCluster{} },
			func() *v1beta1.MultiKueueClusterList { return &v1beta1.MultiKueueClusterList{} },
			func(dst, src *v1beta1.MultiKueueClusterList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.MultiKueueClusterList) []*v1beta1.MultiKueueCluster {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta1.MultiKueueClusterList, items []*v1beta1.MultiKueueCluster) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
