/*

 */
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"
	v1beta1 "sigs.k8s.io/kueue/apis/kueue/v1beta1"
	kueuev1beta1 "sigs.k8s.io/kueue/client-go/applyconfiguration/kueue/v1beta1"
	typedkueuev1beta1 "sigs.k8s.io/kueue/client-go/clientset/versioned/typed/kueue/v1beta1"
)

// fakeLocalQueues implements LocalQueueInterface
type fakeLocalQueues struct {
	*gentype.FakeClientWithListAndApply[*v1beta1.LocalQueue, *v1beta1.LocalQueueList, *kueuev1beta1.LocalQueueApplyConfiguration]
	Fake *FakeKueueV1beta1
}

func newFakeLocalQueues(fake *FakeKueueV1beta1, namespace string) typedkueuev1beta1.LocalQueueInterface {
	return &fakeLocalQueues{
		gentype.NewFakeClientWithListAndApply[*v1beta1.LocalQueue, *v1beta1.LocalQueueList, *kueuev1beta1.LocalQueueApplyConfiguration](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("localqueues"),
			v1beta1.SchemeGroupVersion.WithKind("LocalQueue"),
			func() *v1beta1.LocalQueue { return &v1beta1.LocalQueue{} },
			func() *v1beta1.LocalQueueList { return &v1beta1.LocalQueueList{} },
			func(dst, src *v1beta1.LocalQueueList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.LocalQueueList) []*v1beta1.LocalQueue { return gentype.ToPointerSlice(list.Items) },
			func(list *v1beta1.LocalQueueList, items []*v1beta1.LocalQueue) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
