/*

 */
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"
	v1beta1 "sigs.k8s.io/kueue/apis/kueue/v1beta1"
	kueuev1beta1 "sigs.k8s.io/kueue/client-go/applyconfiguration/kueue/v1beta1"
	typedkueuev1beta1 "sigs.k8s.io/kueue/client-go/clientset/versioned/typed/kueue/v1beta1"
)

// fakeProvisioningRequestConfigs implements ProvisioningRequestConfigInterface
type fakeProvisioningRequestConfigs struct {
	*gentype.FakeClientWithListAndApply[*v1beta1.ProvisioningRequestConfig, *v1beta1.ProvisioningRequestConfigList, *kueuev1beta1.ProvisioningRequestConfigApplyConfiguration]
	Fake *FakeKueueV1beta1
}

func newFakeProvisioningRequestConfigs(fake *FakeKueueV1beta1) typedkueuev1beta1.ProvisioningRequestConfigInterface {
	return &fakeProvisioningRequestConfigs{
		gentype.NewFakeClientWithListAndApply[*v1beta1.ProvisioningRequestConfig, *v1beta1.ProvisioningRequestConfigList, *kueuev1beta1.ProvisioningRequestConfigApplyConfiguration](
			fake.Fake,
			"",
			v1beta1.SchemeGroupVersion.WithResource("provisioningrequestconfigs"),
			v1beta1.SchemeGroupVersion.WithKind("ProvisioningRequestConfig"),
			func() *v1beta1.ProvisioningRequestConfig { return &v1beta1.ProvisioningRequestConfig{} },
			func() *v1beta1.ProvisioningRequestConfigList { return &v1beta1.ProvisioningRequestConfigList{} },
			func(dst, src *v1beta1.ProvisioningRequestConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.ProvisioningRequestConfigList) []*v1beta1.ProvisioningRequestConfig {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta1.ProvisioningRequestConfigList, items []*v1beta1.ProvisioningRequestConfig) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
