apiVersion: config.kueue.x-k8s.io/v1beta1
kind: Configuration
health:
  healthProbeBindAddress: :8081
metrics:
  bindAddress: :8443
# enableClusterQueueResources: true   # 是否自动创建 ClusterQueue 所需的资源对象
webhook:
  port: 9443
leaderElection:
  leaderElect: true
  resourceName: c1f6bfd2.kueue.x-k8s.io
controller: # 每种资源的最大并发控制数量，比如最多可以并行处理 5 个 Job，每个控制器可以避免过载。
  groupKindConcurrency:
    Job.batch: 5
    Pod: 5
    Workload.kueue.x-k8s.io: 5
    LocalQueue.kueue.x-k8s.io: 1
    Cohort.kueue.x-k8s.io: 1
    ClusterQueue.kueue.x-k8s.io: 1
    ResourceFlavor.kueue.x-k8s.io: 1
clientConnection:
  qps: 50
  burst: 100
#pprofBindAddress: :8083
#waitForPodsReady:   # 是否启用在资源准备好前等待 Pod，支持退避机制（Backoff），可控制 Admission 阶段是否阻塞。
#  enable: false
#  timeout: 5m
#  recoveryTimeout: 3m
#  blockAdmission: false
#  requeuingStrategy:
#    timestamp: Eviction
#    backoffLimitCount: null # null indicates infinite requeuing
#    backoffBaseSeconds: 60
#    backoffMaxSeconds: 3600
#manageJobsWithoutQueueName: true
managedJobsNamespaceSelector:
  matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values: [ kube-system, kueue-system ]
#internalCertManagement:
#  enable: false
#  webhookServiceName: ""
#  webhookSecretName: ""
integrations:       # 启用了和哪些资源的集成
  frameworks:
#    - "batch/job"
  - "pod"
  - "deployment" # requires enabling pod integration
  - "statefulset" # requires enabling pod integration
  - "leaderworkerset.x-k8s.io/leaderworkerset" # requires enabling pod integration
#  externalFrameworks:
#  - "Foo.v1.example.com"
  labelKeysToCopy:


#fairSharing: #  公平共享配置
#  enable: true
#  preemptionStrategies: [LessThanOrEqualToFinalShare, LessThanInitialShare]
#admissionFairSharing:  # 用于基于资源使用量的公平调度策略，设置不同资源的权重。比如忽略 CPU 和内存，仅关注 GPU 使用。
#  usageHalfLifeTime: "168h" # 7 days
#  usageSamplingInterval: "5m"
#  resourceWeights: # optional, defaults to 1 for all resources if not specified
#    cpu: 0    # if you want to completely ignore cpu usage
#    memory: 0 # ignore completely memory usage
#    example.com/gpu: 100 # and you care only about GPUs usage
#resources:
#  excludeResourcePrefixes: []
#  transformations:
#  - input: nvidia.com/mig-4g.5gb
#    strategy: Replace | Retain
#    outputs:
#      example.com/accelerator-memory: 5Gi
#      example.com/accelerator-gpc: 4
objectRetentionPolicies: # 对象保留策略
  workloads:
    afterFinished: null # null indicates infinite retention, 0s means no retention at all
    afterDeactivatedByKueue: null # null indicates infinite retention, 0s means no retention at all
