apiVersion: apps/v1
kind: Deployment
metadata:
  name: kueue-controller-manager
  namespace: kueue-system
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: kueue
    control-plane: controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: kueue
        control-plane: controller-manager
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      volumes:
        - name: visibility
          emptyDir: {}
        - name: cert
          secret:
            secretName: kueue-webhook-server-cert
            defaultMode: 420
        - name: manager-config
          configMap:
            name: kueue-manager-config
            defaultMode: 420
      containers:
        - name: manager
          image: registry.k8s.io/kueue/kueue:v0.12.4
          command:
            - /manager
          args:
            - '--config=/controller_manager_config.yaml'
            - '--zap-log-level=3'
          ports:
            - name: metrics
              containerPort: 8443
              protocol: TCP
            - name: visibility
              containerPort: 8082
              protocol: TCP
            - name: webhook-server
              containerPort: 9443
              protocol: TCP
          volumeMounts:
            - name: visibility
              mountPath: /visibility
            - name: cert
              readOnly: true
              mountPath: /tmp/k8s-webhook-server/serving-certs
            - name: manager-config
              mountPath: /controller_manager_config.yaml
              subPath: controller_manager_config.yaml
      serviceAccountName: kueue-controller-manager
      securityContext:
        runAsNonRoot: false
