/*

 */
// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	internalinterfaces "sigs.k8s.io/kueue/client-go/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ClusterQueues returns a ClusterQueueInformer.
	ClusterQueues() ClusterQueueInformer
	// LocalQueues returns a LocalQueueInformer.
	LocalQueues() LocalQueueInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// ClusterQueues returns a ClusterQueueInformer.
func (v *version) ClusterQueues() ClusterQueueInformer {
	return &clusterQueueInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// LocalQueues returns a LocalQueueInformer.
func (v *version) LocalQueues() LocalQueueInformer {
	return &localQueueInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
