apiVersion: v1
kind: Pod
metadata:
  name: kueue-sleep
  labels:
    kueue.x-k8s.io/queue-name: user-queue
  namespace: default
spec:
  containers:
    - name: sleep
      image: registry.cn-hangzhou.aliyuncs.com/acejilam/busybox
      command:
        - sleep
      args:
        - 3s
      resources:
        requests:
          cpu: 3
  restartPolicy: OnFailure