// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	kueuev1beta1 "sigs.k8s.io/kueue/apis/kueue/v1beta1"
)

// AdmissionCheckLister helps list AdmissionChecks.
// All objects returned here must be treated as read-only.
type AdmissionCheckLister interface {
	// List lists all AdmissionChecks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kueuev1beta1.AdmissionCheck, err error)
	// Get retrieves the AdmissionCheck from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kueuev1beta1.AdmissionCheck, error)
	AdmissionCheckListerExpansion
}

// admissionCheckLister implements the AdmissionCheckLister interface.
type admissionCheckLister struct {
	listers.ResourceIndexer[*kueuev1beta1.AdmissionCheck]
}

// NewAdmissionCheckLister returns a new AdmissionCheckLister.
func NewAdmissionCheckLister(indexer cache.Indexer) AdmissionCheckLister {
	return &admissionCheckLister{listers.New[*kueuev1beta1.AdmissionCheck](indexer, kueuev1beta1.Resource("admissioncheck"))}
}
