/*

 */
// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// AdmissionCheckListerExpansion allows custom methods to be added to
// AdmissionCheckLister.
type AdmissionCheckListerExpansion interface{}

// ClusterQueueListerExpansion allows custom methods to be added to
// ClusterQueueLister.
type ClusterQueueListerExpansion interface{}

// CohortListerExpansion allows custom methods to be added to
// CohortLister.
type CohortListerExpansion interface{}

// CohortNamespaceListerExpansion allows custom methods to be added to
// CohortNamespaceLister.
type CohortNamespaceListerExpansion interface{}

// LocalQueueListerExpansion allows custom methods to be added to
// LocalQueueLister.
type LocalQueueListerExpansion interface{}

// LocalQueueNamespaceListerExpansion allows custom methods to be added to
// LocalQueueNamespaceLister.
type LocalQueueNamespaceListerExpansion interface{}

// MultiKueueClusterListerExpansion allows custom methods to be added to
// MultiKueueClusterLister.
type MultiKueueClusterListerExpansion interface{}

// MultiKueueConfigListerExpansion allows custom methods to be added to
// MultiKueueConfigLister.
type MultiKueueConfigListerExpansion interface{}

// ProvisioningRequestConfigListerExpansion allows custom methods to be added to
// ProvisioningRequestConfigLister.
type ProvisioningRequestConfigListerExpansion interface{}

// ResourceFlavorListerExpansion allows custom methods to be added to
// ResourceFlavorLister.
type ResourceFlavorListerExpansion interface{}

// WorkloadListerExpansion allows custom methods to be added to
// WorkloadLister.
type WorkloadListerExpansion interface{}

// WorkloadNamespaceListerExpansion allows custom methods to be added to
// WorkloadNamespaceLister.
type WorkloadNamespaceListerExpansion interface{}

// WorkloadPriorityClassListerExpansion allows custom methods to be added to
// WorkloadPriorityClassLister.
type WorkloadPriorityClassListerExpansion interface{}
