// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	kueuev1beta1 "sigs.k8s.io/kueue/apis/kueue/v1beta1"
)

// LocalQueueLister helps list LocalQueues.
// All objects returned here must be treated as read-only.
type LocalQueueLister interface {
	// List lists all LocalQueues in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kueuev1beta1.LocalQueue, err error)
	// LocalQueues returns an object that can list and get LocalQueues.
	LocalQueues(namespace string) LocalQueueNamespaceLister
	LocalQueueListerExpansion
}

// localQueueLister implements the LocalQueueLister interface.
type localQueueLister struct {
	listers.ResourceIndexer[*kueuev1beta1.LocalQueue]
}

// NewLocalQueueLister returns a new LocalQueueLister.
func NewLocalQueueLister(indexer cache.Indexer) LocalQueueLister {
	return &localQueueLister{listers.New[*kueuev1beta1.LocalQueue](indexer, kueuev1beta1.Resource("localqueue"))}
}

// LocalQueues returns an object that can list and get LocalQueues.
func (s *localQueueLister) LocalQueues(namespace string) LocalQueueNamespaceLister {
	return localQueueNamespaceLister{listers.NewNamespaced[*kueuev1beta1.LocalQueue](s.ResourceIndexer, namespace)}
}

// LocalQueueNamespaceLister helps list and get LocalQueues.
// All objects returned here must be treated as read-only.
type LocalQueueNamespaceLister interface {
	// List lists all LocalQueues in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kueuev1beta1.LocalQueue, err error)
	// Get retrieves the LocalQueue from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kueuev1beta1.LocalQueue, error)
	LocalQueueNamespaceListerExpansion
}

// localQueueNamespaceLister implements the LocalQueueNamespaceLister
// interface.
type localQueueNamespaceLister struct {
	listers.ResourceIndexer[*kueuev1beta1.LocalQueue]
}
