// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	kueuev1beta1 "sigs.k8s.io/kueue/apis/kueue/v1beta1"
)

// MultiKueueClusterLister helps list MultiKueueClusters.
// All objects returned here must be treated as read-only.
type MultiKueueClusterLister interface {
	// List lists all MultiKueueClusters in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kueuev1beta1.MultiKueueCluster, err error)
	// Get retrieves the MultiKueueCluster from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kueuev1beta1.MultiKueueCluster, error)
	MultiKueueClusterListerExpansion
}

// multiKueueClusterLister implements the MultiKueueClusterLister interface.
type multiKueueClusterLister struct {
	listers.ResourceIndexer[*kueuev1beta1.MultiKueueCluster]
}

// NewMultiKueueClusterLister returns a new MultiKueueClusterLister.
func NewMultiKueueClusterLister(indexer cache.Indexer) MultiKueueClusterLister {
	return &multiKueueClusterLister{listers.New[*kueuev1beta1.MultiKueueCluster](indexer, kueuev1beta1.Resource("multikueuecluster"))}
}
