// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	kueuev1beta1 "sigs.k8s.io/kueue/apis/kueue/v1beta1"
)

// MultiKueueConfigLister helps list MultiKueueConfigs.
// All objects returned here must be treated as read-only.
type MultiKueueConfigLister interface {
	// List lists all MultiKueueConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kueuev1beta1.MultiKueueConfig, err error)
	// Get retrieves the MultiKueueConfig from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kueuev1beta1.MultiKueueConfig, error)
	MultiKueueConfigListerExpansion
}

// multiKueueConfigLister implements the MultiKueueConfigLister interface.
type multiKueueConfigLister struct {
	listers.ResourceIndexer[*kueuev1beta1.MultiKueueConfig]
}

// NewMultiKueueConfigLister returns a new MultiKueueConfigLister.
func NewMultiKueueConfigLister(indexer cache.Indexer) MultiKueueConfigLister {
	return &multiKueueConfigLister{listers.New[*kueuev1beta1.MultiKueueConfig](indexer, kueuev1beta1.Resource("multikueueconfig"))}
}
