// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	kueuev1beta1 "sigs.k8s.io/kueue/apis/kueue/v1beta1"
)

// ResourceFlavorLister helps list ResourceFlavors.
// All objects returned here must be treated as read-only.
type ResourceFlavorLister interface {
	// List lists all ResourceFlavors in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kueuev1beta1.ResourceFlavor, err error)
	// Get retrieves the ResourceFlavor from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kueuev1beta1.ResourceFlavor, error)
	ResourceFlavorListerExpansion
}

// resourceFlavorLister implements the ResourceFlavorLister interface.
type resourceFlavorLister struct {
	listers.ResourceIndexer[*kueuev1beta1.ResourceFlavor]
}

// NewResourceFlavorLister returns a new ResourceFlavorLister.
func NewResourceFlavorLister(indexer cache.Indexer) ResourceFlavorLister {
	return &resourceFlavorLister{listers.New[*kueuev1beta1.ResourceFlavor](indexer, kueuev1beta1.Resource("resourceflavor"))}
}
