/*

 */
// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	kueuev1beta1 "sigs.k8s.io/kueue/apis/kueue/v1beta1"
)

// WorkloadPriorityClassLister helps list WorkloadPriorityClasses.
// All objects returned here must be treated as read-only.
type WorkloadPriorityClassLister interface {
	// List lists all WorkloadPriorityClasses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kueuev1beta1.WorkloadPriorityClass, err error)
	// Get retrieves the WorkloadPriorityClass from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kueuev1beta1.WorkloadPriorityClass, error)
	WorkloadPriorityClassListerExpansion
}

// workloadPriorityClassLister implements the WorkloadPriorityClassLister interface.
type workloadPriorityClassLister struct {
	listers.ResourceIndexer[*kueuev1beta1.WorkloadPriorityClass]
}

// NewWorkloadPriorityClassLister returns a new WorkloadPriorityClassLister.
func NewWorkloadPriorityClassLister(indexer cache.Indexer) WorkloadPriorityClassLister {
	return &workloadPriorityClassLister{listers.New[*kueuev1beta1.WorkloadPriorityClass](indexer, kueuev1beta1.Resource("workloadpriorityclass"))}
}
