/*

 */
// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// ClusterQueueListerExpansion allows custom methods to be added to
// ClusterQueueLister.
type ClusterQueueListerExpansion interface{}

// LocalQueueListerExpansion allows custom methods to be added to
// LocalQueueLister.
type LocalQueueListerExpansion interface{}

// LocalQueueNamespaceListerExpansion allows custom methods to be added to
// LocalQueueNamespaceLister.
type LocalQueueNamespaceListerExpansion interface{}
