// Package v1beta1 contains API Schema definitions for the pending workloads kueue v1beta1 API group
// +kubebuilder:object:generate=true
// +kubebuilder:skip
// +groupName=visibility.kueue.x-k8s.io
// +k8s:openapi-gen=true
// +k8s:conversion-gen=false

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/scheme"
)

var (
	// GroupVersion is group version used to register these objects.
	GroupVersion = schema.GroupVersion{Group: "visibility.kueue.x-k8s.io", Version: "v1beta1"}

	// SchemeGroupVersion is alias to GroupVersion for client-go libraries.
	// It is required by pkg/client/informers/externalversions/...
	SchemeGroupVersion = GroupVersion

	// SchemeBuilder is used to add go types to the GroupVersionKind scheme
	SchemeBuilder = &scheme.Builder{GroupVersion: GroupVersion}

	// localSchemeBuilder is used to register autogenerated conversion and defaults functions
	// It is required by ./zz_generated.conversion.go and ./zz_generated.defaults.go
	localSchemeBuilder = &SchemeBuilder.SchemeBuilder

	// AddToScheme adds the types in this group-version to the given scheme.
	AddToScheme = SchemeBuilder.AddToScheme
)

// Resource is required by pkg/client/listers/...
func Resource(resource string) schema.GroupResource {
	return GroupVersion.WithResource(resource).GroupResource()
}
