// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	kueuev1beta1 "sigs.k8s.io/kueue/apis/kueue/v1beta1"
)

// AdmissionCheckStateApplyConfiguration represents a declarative configuration of the AdmissionCheckState type for use
// with apply.
type AdmissionCheckStateApplyConfiguration struct {
	Name               *kueuev1beta1.AdmissionCheckReference `json:"name,omitempty"`
	State              *kueuev1beta1.CheckState              `json:"state,omitempty"`
	LastTransitionTime *v1.Time                              `json:"lastTransitionTime,omitempty"`
	Message            *string                               `json:"message,omitempty"`
	PodSetUpdates      []PodSetUpdateApplyConfiguration      `json:"podSetUpdates,omitempty"`
}

// AdmissionCheckStateApplyConfiguration constructs a declarative configuration of the AdmissionCheckState type for use with
// apply.
func AdmissionCheckState() *AdmissionCheckStateApplyConfiguration {
	return &AdmissionCheckStateApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AdmissionCheckStateApplyConfiguration) WithName(value kueuev1beta1.AdmissionCheckReference) *AdmissionCheckStateApplyConfiguration {
	b.Name = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *AdmissionCheckStateApplyConfiguration) WithState(value kueuev1beta1.CheckState) *AdmissionCheckStateApplyConfiguration {
	b.State = &value
	return b
}

// WithLastTransitionTime sets the LastTransitionTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastTransitionTime field is set to the value of the last call.
func (b *AdmissionCheckStateApplyConfiguration) WithLastTransitionTime(value v1.Time) *AdmissionCheckStateApplyConfiguration {
	b.LastTransitionTime = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *AdmissionCheckStateApplyConfiguration) WithMessage(value string) *AdmissionCheckStateApplyConfiguration {
	b.Message = &value
	return b
}

// WithPodSetUpdates adds the given value to the PodSetUpdates field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PodSetUpdates field.
func (b *AdmissionCheckStateApplyConfiguration) WithPodSetUpdates(values ...*PodSetUpdateApplyConfiguration) *AdmissionCheckStateApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPodSetUpdates")
		}
		b.PodSetUpdates = append(b.PodSetUpdates, *values[i])
	}
	return b
}
