/*

 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	kueuev1beta1 "sigs.k8s.io/kueue/apis/kueue/v1beta1"
)

// AdmissionScopeApplyConfiguration represents a declarative configuration of the AdmissionScope type for use
// with apply.
type AdmissionScopeApplyConfiguration struct {
	AdmissionMode *kueuev1beta1.AdmissionMode `json:"admissionMode,omitempty"`
}

// AdmissionScopeApplyConfiguration constructs a declarative configuration of the AdmissionScope type for use with
// apply.
func AdmissionScope() *AdmissionScopeApplyConfiguration {
	return &AdmissionScopeApplyConfiguration{}
}

// WithAdmissionMode sets the AdmissionMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdmissionMode field is set to the value of the last call.
func (b *AdmissionScopeApplyConfiguration) WithAdmissionMode(value kueuev1beta1.AdmissionMode) *AdmissionScopeApplyConfiguration {
	b.AdmissionMode = &value
	return b
}
