/*

 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// AdmissionCheckParametersReferenceApplyConfiguration represents a declarative configuration of the AdmissionCheckParametersReference type for use
// with apply.
type AdmissionCheckParametersReferenceApplyConfiguration struct {
	APIGroup *string `json:"apiGroup,omitempty"`
	Kind     *string `json:"kind,omitempty"`
	Name     *string `json:"name,omitempty"`
}

// AdmissionCheckParametersReferenceApplyConfiguration constructs a declarative configuration of the AdmissionCheckParametersReference type for use with
// apply.
func AdmissionCheckParametersReference() *AdmissionCheckParametersReferenceApplyConfiguration {
	return &AdmissionCheckParametersReferenceApplyConfiguration{}
}

// WithAPIGroup sets the APIGroup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIGroup field is set to the value of the last call.
func (b *AdmissionCheckParametersReferenceApplyConfiguration) WithAPIGroup(value string) *AdmissionCheckParametersReferenceApplyConfiguration {
	b.APIGroup = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *AdmissionCheckParametersReferenceApplyConfiguration) WithKind(value string) *AdmissionCheckParametersReferenceApplyConfiguration {
	b.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AdmissionCheckParametersReferenceApplyConfiguration) WithName(value string) *AdmissionCheckParametersReferenceApplyConfiguration {
	b.Name = &value
	return b
}
