// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// AdmissionChecksStrategyApplyConfiguration represents a declarative configuration of the AdmissionChecksStrategy type for use
// with apply.
type AdmissionChecksStrategyApplyConfiguration struct {
	AdmissionChecks []AdmissionCheckStrategyRuleApplyConfiguration `json:"admissionChecks,omitempty"`
}

// AdmissionChecksStrategyApplyConfiguration constructs a declarative configuration of the AdmissionChecksStrategy type for use with
// apply.
func AdmissionChecksStrategy() *AdmissionChecksStrategyApplyConfiguration {
	return &AdmissionChecksStrategyApplyConfiguration{}
}

// WithAdmissionChecks adds the given value to the AdmissionChecks field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AdmissionChecks field.
func (b *AdmissionChecksStrategyApplyConfiguration) WithAdmissionChecks(values ...*AdmissionCheckStrategyRuleApplyConfiguration) *AdmissionChecksStrategyApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAdmissionChecks")
		}
		b.AdmissionChecks = append(b.AdmissionChecks, *values[i])
	}
	return b
}
