/*

 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AdmissionFairSharingStatusApplyConfiguration represents a declarative configuration of the AdmissionFairSharingStatus type for use
// with apply.
type AdmissionFairSharingStatusApplyConfiguration struct {
	ConsumedResources *v1.ResourceList `json:"consumedResources,omitempty"`
	LastUpdate        *metav1.Time     `json:"lastUpdate,omitempty"`
}

// AdmissionFairSharingStatusApplyConfiguration constructs a declarative configuration of the AdmissionFairSharingStatus type for use with
// apply.
func AdmissionFairSharingStatus() *AdmissionFairSharingStatusApplyConfiguration {
	return &AdmissionFairSharingStatusApplyConfiguration{}
}

// WithConsumedResources sets the ConsumedResources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConsumedResources field is set to the value of the last call.
func (b *AdmissionFairSharingStatusApplyConfiguration) WithConsumedResources(value v1.ResourceList) *AdmissionFairSharingStatusApplyConfiguration {
	b.ConsumedResources = &value
	return b
}

// WithLastUpdate sets the LastUpdate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastUpdate field is set to the value of the last call.
func (b *AdmissionFairSharingStatusApplyConfiguration) WithLastUpdate(value metav1.Time) *AdmissionFairSharingStatusApplyConfiguration {
	b.LastUpdate = &value
	return b
}
