/*

 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	kueuev1beta1 "sigs.k8s.io/kueue/apis/kueue/v1beta1"
)

// BorrowWithinCohortApplyConfiguration represents a declarative configuration of the BorrowWithinCohort type for use
// with apply.
type BorrowWithinCohortApplyConfiguration struct {
	Policy               *kueuev1beta1.BorrowWithinCohortPolicy `json:"policy,omitempty"`
	MaxPriorityThreshold *int32                                 `json:"maxPriorityThreshold,omitempty"`
}

// BorrowWithinCohortApplyConfiguration constructs a declarative configuration of the BorrowWithinCohort type for use with
// apply.
func BorrowWithinCohort() *BorrowWithinCohortApplyConfiguration {
	return &BorrowWithinCohortApplyConfiguration{}
}

// WithPolicy sets the Policy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Policy field is set to the value of the last call.
func (b *BorrowWithinCohortApplyConfiguration) WithPolicy(value kueuev1beta1.BorrowWithinCohortPolicy) *BorrowWithinCohortApplyConfiguration {
	b.Policy = &value
	return b
}

// WithMaxPriorityThreshold sets the MaxPriorityThreshold field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxPriorityThreshold field is set to the value of the last call.
func (b *BorrowWithinCohortApplyConfiguration) WithMaxPriorityThreshold(value int32) *BorrowWithinCohortApplyConfiguration {
	b.MaxPriorityThreshold = &value
	return b
}
