// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ClusterQueuePendingWorkloadApplyConfiguration represents a declarative configuration of the ClusterQueuePendingWorkload type for use
// with apply.
type ClusterQueuePendingWorkloadApplyConfiguration struct {
	Name      *string `json:"name,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
}

// ClusterQueuePendingWorkloadApplyConfiguration constructs a declarative configuration of the ClusterQueuePendingWorkload type for use with
// apply.
func ClusterQueuePendingWorkload() *ClusterQueuePendingWorkloadApplyConfiguration {
	return &ClusterQueuePendingWorkloadApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ClusterQueuePendingWorkloadApplyConfiguration) WithName(value string) *ClusterQueuePendingWorkloadApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ClusterQueuePendingWorkloadApplyConfiguration) WithNamespace(value string) *ClusterQueuePendingWorkloadApplyConfiguration {
	b.Namespace = &value
	return b
}
