// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ClusterQueuePendingWorkloadsStatusApplyConfiguration represents a declarative configuration of the ClusterQueuePendingWorkloadsStatus type for use
// with apply.
type ClusterQueuePendingWorkloadsStatusApplyConfiguration struct {
	Head           []ClusterQueuePendingWorkloadApplyConfiguration `json:"clusterQueuePendingWorkload,omitempty"`
	LastChangeTime *v1.Time                                        `json:"lastChangeTime,omitempty"`
}

// ClusterQueuePendingWorkloadsStatusApplyConfiguration constructs a declarative configuration of the ClusterQueuePendingWorkloadsStatus type for use with
// apply.
func ClusterQueuePendingWorkloadsStatus() *ClusterQueuePendingWorkloadsStatusApplyConfiguration {
	return &ClusterQueuePendingWorkloadsStatusApplyConfiguration{}
}

// WithHead adds the given value to the Head field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Head field.
func (b *ClusterQueuePendingWorkloadsStatusApplyConfiguration) WithHead(values ...*ClusterQueuePendingWorkloadApplyConfiguration) *ClusterQueuePendingWorkloadsStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithHead")
		}
		b.Head = append(b.Head, *values[i])
	}
	return b
}

// WithLastChangeTime sets the LastChangeTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastChangeTime field is set to the value of the last call.
func (b *ClusterQueuePendingWorkloadsStatusApplyConfiguration) WithLastChangeTime(value v1.Time) *ClusterQueuePendingWorkloadsStatusApplyConfiguration {
	b.LastChangeTime = &value
	return b
}
