/*

 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	kueuev1beta1 "sigs.k8s.io/kueue/apis/kueue/v1beta1"
)

// ClusterQueuePreemptionApplyConfiguration represents a declarative configuration of the ClusterQueuePreemption type for use
// with apply.
type ClusterQueuePreemptionApplyConfiguration struct {
	ReclaimWithinCohort *kueuev1beta1.PreemptionPolicy        `json:"reclaimWithinCohort,omitempty"`
	BorrowWithinCohort  *BorrowWithinCohortApplyConfiguration `json:"borrowWithinCohort,omitempty"`
	WithinClusterQueue  *kueuev1beta1.PreemptionPolicy        `json:"withinClusterQueue,omitempty"`
}

// ClusterQueuePreemptionApplyConfiguration constructs a declarative configuration of the ClusterQueuePreemption type for use with
// apply.
func ClusterQueuePreemption() *ClusterQueuePreemptionApplyConfiguration {
	return &ClusterQueuePreemptionApplyConfiguration{}
}

// WithReclaimWithinCohort sets the ReclaimWithinCohort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReclaimWithinCohort field is set to the value of the last call.
func (b *ClusterQueuePreemptionApplyConfiguration) WithReclaimWithinCohort(value kueuev1beta1.PreemptionPolicy) *ClusterQueuePreemptionApplyConfiguration {
	b.ReclaimWithinCohort = &value
	return b
}

// WithBorrowWithinCohort sets the BorrowWithinCohort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BorrowWithinCohort field is set to the value of the last call.
func (b *ClusterQueuePreemptionApplyConfiguration) WithBorrowWithinCohort(value *BorrowWithinCohortApplyConfiguration) *ClusterQueuePreemptionApplyConfiguration {
	b.BorrowWithinCohort = value
	return b
}

// WithWithinClusterQueue sets the WithinClusterQueue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WithinClusterQueue field is set to the value of the last call.
func (b *ClusterQueuePreemptionApplyConfiguration) WithWithinClusterQueue(value kueuev1beta1.PreemptionPolicy) *ClusterQueuePreemptionApplyConfiguration {
	b.WithinClusterQueue = &value
	return b
}
