// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// FairSharingApplyConfiguration represents a declarative configuration of the FairSharing type for use
// with apply.
type FairSharingApplyConfiguration struct {
	Weight *resource.Quantity `json:"weight,omitempty"`
}

// FairSharingApplyConfiguration constructs a declarative configuration of the FairSharing type for use with
// apply.
func FairSharing() *FairSharingApplyConfiguration {
	return &FairSharingApplyConfiguration{}
}

// WithWeight sets the Weight field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Weight field is set to the value of the last call.
func (b *FairSharingApplyConfiguration) WithWeight(value resource.Quantity) *FairSharingApplyConfiguration {
	b.Weight = &value
	return b
}
