/*

 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	kueuev1beta1 "sigs.k8s.io/kueue/apis/kueue/v1beta1"
)

// KubeConfigApplyConfiguration represents a declarative configuration of the KubeConfig type for use
// with apply.
type KubeConfigApplyConfiguration struct {
	Location     *string                    `json:"location,omitempty"`
	LocationType *kueuev1beta1.LocationType `json:"locationType,omitempty"`
}

// KubeConfigApplyConfiguration constructs a declarative configuration of the KubeConfig type for use with
// apply.
func KubeConfig() *KubeConfigApplyConfiguration {
	return &KubeConfigApplyConfiguration{}
}

// WithLocation sets the Location field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Location field is set to the value of the last call.
func (b *KubeConfigApplyConfiguration) WithLocation(value string) *KubeConfigApplyConfiguration {
	b.Location = &value
	return b
}

// WithLocationType sets the LocationType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocationType field is set to the value of the last call.
func (b *KubeConfigApplyConfiguration) WithLocationType(value kueuev1beta1.LocationType) *KubeConfigApplyConfiguration {
	b.LocationType = &value
	return b
}
