/*

 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// LocalQueueResourceUsageApplyConfiguration represents a declarative configuration of the LocalQueueResourceUsage type for use
// with apply.
type LocalQueueResourceUsageApplyConfiguration struct {
	Name  *v1.ResourceName   `json:"name,omitempty"`
	Total *resource.Quantity `json:"total,omitempty"`
}

// LocalQueueResourceUsageApplyConfiguration constructs a declarative configuration of the LocalQueueResourceUsage type for use with
// apply.
func LocalQueueResourceUsage() *LocalQueueResourceUsageApplyConfiguration {
	return &LocalQueueResourceUsageApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *LocalQueueResourceUsageApplyConfiguration) WithName(value v1.ResourceName) *LocalQueueResourceUsageApplyConfiguration {
	b.Name = &value
	return b
}

// WithTotal sets the Total field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Total field is set to the value of the last call.
func (b *LocalQueueResourceUsageApplyConfiguration) WithTotal(value resource.Quantity) *LocalQueueResourceUsageApplyConfiguration {
	b.Total = &value
	return b
}
