/*

 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// MultiKueueClusterStatusApplyConfiguration represents a declarative configuration of the MultiKueueClusterStatus type for use
// with apply.
type MultiKueueClusterStatusApplyConfiguration struct {
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// MultiKueueClusterStatusApplyConfiguration constructs a declarative configuration of the MultiKueueClusterStatus type for use with
// apply.
func MultiKueueClusterStatus() *MultiKueueClusterStatusApplyConfiguration {
	return &MultiKueueClusterStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *MultiKueueClusterStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *MultiKueueClusterStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
