/*

 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// MultiKueueConfigSpecApplyConfiguration represents a declarative configuration of the MultiKueueConfigSpec type for use
// with apply.
type MultiKueueConfigSpecApplyConfiguration struct {
	Clusters []string `json:"clusters,omitempty"`
}

// MultiKueueConfigSpecApplyConfiguration constructs a declarative configuration of the MultiKueueConfigSpec type for use with
// apply.
func MultiKueueConfigSpec() *MultiKueueConfigSpecApplyConfiguration {
	return &MultiKueueConfigSpecApplyConfiguration{}
}

// WithClusters adds the given value to the Clusters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Clusters field.
func (b *MultiKueueConfigSpecApplyConfiguration) WithClusters(values ...string) *MultiKueueConfigSpecApplyConfiguration {
	for i := range values {
		b.Clusters = append(b.Clusters, values[i])
	}
	return b
}
