// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// MultiKueueClusterSpecApplyConfiguration represents a declarative configuration of the MultiKueueClusterSpec type for use
// with apply.
type MultiKueueClusterSpecApplyConfiguration struct {
	KubeConfig *KubeConfigApplyConfiguration `json:"kubeConfig,omitempty"`
}

// MultiKueueClusterSpecApplyConfiguration constructs a declarative configuration of the MultiKueueClusterSpec type for use with
// apply.
func MultiKueueClusterSpec() *MultiKueueClusterSpecApplyConfiguration {
	return &MultiKueueClusterSpecApplyConfiguration{}
}

// WithKubeConfig sets the KubeConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KubeConfig field is set to the value of the last call.
func (b *MultiKueueClusterSpecApplyConfiguration) WithKubeConfig(value *KubeConfigApplyConfiguration) *MultiKueueClusterSpecApplyConfiguration {
	b.KubeConfig = value
	return b
}
