/*

 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// PodSetTopologyRequestApplyConfiguration represents a declarative configuration of the PodSetTopologyRequest type for use
// with apply.
type PodSetTopologyRequestApplyConfiguration struct {
	Required                    *string `json:"required,omitempty"`
	Preferred                   *string `json:"preferred,omitempty"`
	Unconstrained               *bool   `json:"unconstrained,omitempty"`
	PodIndexLabel               *string `json:"podIndexLabel,omitempty"`
	SubGroupIndexLabel          *string `json:"subGroupIndexLabel,omitempty"`
	SubGroupCount               *int32  `json:"subGroupCount,omitempty"`
	PodSetSliceRequiredTopology *string `json:"podSetSliceRequiredTopology,omitempty"`
	PodSetSliceSize             *int32  `json:"podSetSliceSize,omitempty"`
}

// PodSetTopologyRequestApplyConfiguration constructs a declarative configuration of the PodSetTopologyRequest type for use with
// apply.
func PodSetTopologyRequest() *PodSetTopologyRequestApplyConfiguration {
	return &PodSetTopologyRequestApplyConfiguration{}
}

// WithRequired sets the Required field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Required field is set to the value of the last call.
func (b *PodSetTopologyRequestApplyConfiguration) WithRequired(value string) *PodSetTopologyRequestApplyConfiguration {
	b.Required = &value
	return b
}

// WithPreferred sets the Preferred field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Preferred field is set to the value of the last call.
func (b *PodSetTopologyRequestApplyConfiguration) WithPreferred(value string) *PodSetTopologyRequestApplyConfiguration {
	b.Preferred = &value
	return b
}

// WithUnconstrained sets the Unconstrained field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Unconstrained field is set to the value of the last call.
func (b *PodSetTopologyRequestApplyConfiguration) WithUnconstrained(value bool) *PodSetTopologyRequestApplyConfiguration {
	b.Unconstrained = &value
	return b
}

// WithPodIndexLabel sets the PodIndexLabel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodIndexLabel field is set to the value of the last call.
func (b *PodSetTopologyRequestApplyConfiguration) WithPodIndexLabel(value string) *PodSetTopologyRequestApplyConfiguration {
	b.PodIndexLabel = &value
	return b
}

// WithSubGroupIndexLabel sets the SubGroupIndexLabel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SubGroupIndexLabel field is set to the value of the last call.
func (b *PodSetTopologyRequestApplyConfiguration) WithSubGroupIndexLabel(value string) *PodSetTopologyRequestApplyConfiguration {
	b.SubGroupIndexLabel = &value
	return b
}

// WithSubGroupCount sets the SubGroupCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SubGroupCount field is set to the value of the last call.
func (b *PodSetTopologyRequestApplyConfiguration) WithSubGroupCount(value int32) *PodSetTopologyRequestApplyConfiguration {
	b.SubGroupCount = &value
	return b
}

// WithPodSetSliceRequiredTopology sets the PodSetSliceRequiredTopology field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodSetSliceRequiredTopology field is set to the value of the last call.
func (b *PodSetTopologyRequestApplyConfiguration) WithPodSetSliceRequiredTopology(value string) *PodSetTopologyRequestApplyConfiguration {
	b.PodSetSliceRequiredTopology = &value
	return b
}

// WithPodSetSliceSize sets the PodSetSliceSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodSetSliceSize field is set to the value of the last call.
func (b *PodSetTopologyRequestApplyConfiguration) WithPodSetSliceSize(value int32) *PodSetTopologyRequestApplyConfiguration {
	b.PodSetSliceSize = &value
	return b
}
