// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
	kueuev1beta1 "sigs.k8s.io/kueue/apis/kueue/v1beta1"
)

// PodSetRequestApplyConfiguration represents a declarative configuration of the PodSetRequest type for use
// with apply.
type PodSetRequestApplyConfiguration struct {
	Name      *kueuev1beta1.PodSetReference `json:"name,omitempty"`
	Resources *v1.ResourceList              `json:"resources,omitempty"`
}

// PodSetRequestApplyConfiguration constructs a declarative configuration of the PodSetRequest type for use with
// apply.
func PodSetRequest() *PodSetRequestApplyConfiguration {
	return &PodSetRequestApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PodSetRequestApplyConfiguration) WithName(value kueuev1beta1.PodSetReference) *PodSetRequestApplyConfiguration {
	b.Name = &value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *PodSetRequestApplyConfiguration) WithResources(value v1.ResourceList) *PodSetRequestApplyConfiguration {
	b.Resources = &value
	return b
}
