/*

 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ProvisioningRequestPodSetUpdatesApplyConfiguration represents a declarative configuration of the ProvisioningRequestPodSetUpdates type for use
// with apply.
type ProvisioningRequestPodSetUpdatesApplyConfiguration struct {
	NodeSelector []ProvisioningRequestPodSetUpdatesNodeSelectorApplyConfiguration `json:"nodeSelector,omitempty"`
}

// ProvisioningRequestPodSetUpdatesApplyConfiguration constructs a declarative configuration of the ProvisioningRequestPodSetUpdates type for use with
// apply.
func ProvisioningRequestPodSetUpdates() *ProvisioningRequestPodSetUpdatesApplyConfiguration {
	return &ProvisioningRequestPodSetUpdatesApplyConfiguration{}
}

// WithNodeSelector adds the given value to the NodeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NodeSelector field.
func (b *ProvisioningRequestPodSetUpdatesApplyConfiguration) WithNodeSelector(values ...*ProvisioningRequestPodSetUpdatesNodeSelectorApplyConfiguration) *ProvisioningRequestPodSetUpdatesApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithNodeSelector")
		}
		b.NodeSelector = append(b.NodeSelector, *values[i])
	}
	return b
}
