// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ProvisioningRequestRetryStrategyApplyConfiguration represents a declarative configuration of the ProvisioningRequestRetryStrategy type for use
// with apply.
type ProvisioningRequestRetryStrategyApplyConfiguration struct {
	BackoffLimitCount  *int32 `json:"backoffLimitCount,omitempty"`
	BackoffBaseSeconds *int32 `json:"backoffBaseSeconds,omitempty"`
	BackoffMaxSeconds  *int32 `json:"backoffMaxSeconds,omitempty"`
}

// ProvisioningRequestRetryStrategyApplyConfiguration constructs a declarative configuration of the ProvisioningRequestRetryStrategy type for use with
// apply.
func ProvisioningRequestRetryStrategy() *ProvisioningRequestRetryStrategyApplyConfiguration {
	return &ProvisioningRequestRetryStrategyApplyConfiguration{}
}

// WithBackoffLimitCount sets the BackoffLimitCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackoffLimitCount field is set to the value of the last call.
func (b *ProvisioningRequestRetryStrategyApplyConfiguration) WithBackoffLimitCount(value int32) *ProvisioningRequestRetryStrategyApplyConfiguration {
	b.BackoffLimitCount = &value
	return b
}

// WithBackoffBaseSeconds sets the BackoffBaseSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackoffBaseSeconds field is set to the value of the last call.
func (b *ProvisioningRequestRetryStrategyApplyConfiguration) WithBackoffBaseSeconds(value int32) *ProvisioningRequestRetryStrategyApplyConfiguration {
	b.BackoffBaseSeconds = &value
	return b
}

// WithBackoffMaxSeconds sets the BackoffMaxSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackoffMaxSeconds field is set to the value of the last call.
func (b *ProvisioningRequestRetryStrategyApplyConfiguration) WithBackoffMaxSeconds(value int32) *ProvisioningRequestRetryStrategyApplyConfiguration {
	b.BackoffMaxSeconds = &value
	return b
}
