// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// RequeueStateApplyConfiguration represents a declarative configuration of the RequeueState type for use
// with apply.
type RequeueStateApplyConfiguration struct {
	Count     *int32   `json:"count,omitempty"`
	RequeueAt *v1.Time `json:"requeueAt,omitempty"`
}

// RequeueStateApplyConfiguration constructs a declarative configuration of the RequeueState type for use with
// apply.
func RequeueState() *RequeueStateApplyConfiguration {
	return &RequeueStateApplyConfiguration{}
}

// WithCount sets the Count field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Count field is set to the value of the last call.
func (b *RequeueStateApplyConfiguration) WithCount(value int32) *RequeueStateApplyConfiguration {
	b.Count = &value
	return b
}

// WithRequeueAt sets the RequeueAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequeueAt field is set to the value of the last call.
func (b *RequeueStateApplyConfiguration) WithRequeueAt(value v1.Time) *RequeueStateApplyConfiguration {
	b.RequeueAt = &value
	return b
}
