/*

 */
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
	v1beta1 "sigs.k8s.io/kueue/client-go/clientset/versioned/typed/visibility/v1beta1"
)

type FakeVisibilityV1beta1 struct {
	*testing.Fake
}

func (c *FakeVisibilityV1beta1) ClusterQueues() v1beta1.ClusterQueueInterface {
	return newFakeClusterQueues(c)
}

func (c *FakeVisibilityV1beta1) LocalQueues(namespace string) v1beta1.LocalQueueInterface {
	return newFakeLocalQueues(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeVisibilityV1beta1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
