// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	kueuev1alpha1 "sigs.k8s.io/kueue/apis/kueue/v1alpha1"
)

// TopologyLister helps list Topologies.
// All objects returned here must be treated as read-only.
type TopologyLister interface {
	// List lists all Topologies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kueuev1alpha1.Topology, err error)
	// Get retrieves the Topology from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kueuev1alpha1.Topology, error)
	TopologyListerExpansion
}

// topologyLister implements the TopologyLister interface.
type topologyLister struct {
	listers.ResourceIndexer[*kueuev1alpha1.Topology]
}

// NewTopologyLister returns a new TopologyLister.
func NewTopologyLister(indexer cache.Indexer) TopologyLister {
	return &topologyLister{listers.New[*kueuev1alpha1.Topology](indexer, kueuev1alpha1.Resource("topology"))}
}
