// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
	v1alpha1 "sigs.k8s.io/kueue/client-go/clientset/versioned/typed/kueue/v1alpha1"
)

type FakeKueueV1alpha1 struct {
	*testing.Fake
}

func (c *FakeKueueV1alpha1) Cohorts(namespace string) v1alpha1.CohortInterface {
	return newFakeCohorts(c, namespace)
}

func (c *FakeKueueV1alpha1) Topologies() v1alpha1.TopologyInterface {
	return newFakeTopologies(c)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeKueueV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
