/*

 */
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

type AdmissionCheckExpansion interface{}

type ClusterQueueExpansion interface{}

type CohortExpansion interface{}

type LocalQueueExpansion interface{}

type MultiKueueClusterExpansion interface{}

type MultiKueueConfigExpansion interface{}

type ProvisioningRequestConfigExpansion interface{}

type ResourceFlavorExpansion interface{}

type WorkloadExpansion interface{}

type WorkloadPriorityClassExpansion interface{}
