// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "sigs.k8s.io/kueue/client-go/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Cohorts returns a CohortInformer.
	Cohorts() CohortInformer
	// Topologies returns a TopologyInformer.
	Topologies() TopologyInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Cohorts returns a CohortInformer.
func (v *version) Cohorts() CohortInformer {
	return &cohortInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Topologies returns a TopologyInformer.
func (v *version) Topologies() TopologyInformer {
	return &topologyInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
