// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1beta1 "sigs.k8s.io/kueue/client-go/applyconfiguration/kueue/v1beta1"
)

// CohortStatusApplyConfiguration represents a declarative configuration of the CohortStatus type for use
// with apply.
type CohortStatusApplyConfiguration struct {
	FairSharing *v1beta1.FairSharingStatusApplyConfiguration `json:"fairSharing,omitempty"`
}

// CohortStatusApplyConfiguration constructs a declarative configuration of the CohortStatus type for use with
// apply.
func CohortStatus() *CohortStatusApplyConfiguration {
	return &CohortStatusApplyConfiguration{}
}

// WithFairSharing sets the FairSharing field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FairSharing field is set to the value of the last call.
func (b *CohortStatusApplyConfiguration) WithFairSharing(value *v1beta1.FairSharingStatusApplyConfiguration) *CohortStatusApplyConfiguration {
	b.FairSharing = value
	return b
}
