/*

 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// TopologyLevelApplyConfiguration represents a declarative configuration of the TopologyLevel type for use
// with apply.
type TopologyLevelApplyConfiguration struct {
	NodeLabel *string `json:"nodeLabel,omitempty"`
}

// TopologyLevelApplyConfiguration constructs a declarative configuration of the TopologyLevel type for use with
// apply.
func TopologyLevel() *TopologyLevelApplyConfiguration {
	return &TopologyLevelApplyConfiguration{}
}

// WithNodeLabel sets the NodeLabel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeLabel field is set to the value of the last call.
func (b *TopologyLevelApplyConfiguration) WithNodeLabel(value string) *TopologyLevelApplyConfiguration {
	b.NodeLabel = &value
	return b
}
